using AgentWiki.App.Services;
using AgentWiki.Core.Abstractions;
using AgentWiki.Core.Analysis;
using AgentWiki.Core.Generation;
using AgentWiki.Core.Models;
// LlmRequestOptions lives in Abstractions
using Microsoft.Extensions.Logging.Abstractions;
using Moq;

namespace AgentWiki.Cli.Tests.Services;

public sealed class ArchitectureGeneratorTests
{
    [Fact]
    public void ExtractJsonObject_StripsMarkdownFences()
    {
        var raw = """
            ```json
            { "title": "T", "summary": "S", "systemContext": "C" }
            ```
            """;

        var json = ArchitectureGenerator.ExtractJsonObject(raw);
        json.ShouldContain("\"title\"");
        json.ShouldNotContain("```");
    }

    [Fact]
    public void ParseArchitectureJson_DeserializesStructuredDocument()
    {
        var raw = """
            {
              "title": "Demo Architecture",
              "summary": "A demo system.",
              "systemContext": "CLI talks to core.",
              "layers": [
                { "name": "CLI", "responsibility": "User interface", "keyPaths": ["src/Cli/"] }
              ],
              "keyComponents": [
                { "name": "Program", "path": "src/Cli/Program.cs", "purpose": "Entry point" }
              ],
              "dataFlows": ["User -> CLI -> Core"],
              "decisions": ["Use DI"],
              "gotchas": ["No secrets in logs"],
              "howToExtend": ["Add commands under Commands/"],
              "mermaidDiagram": "flowchart LR\n  A-->B"
            }
            """;

        var doc = ArchitectureGenerator.ParseArchitectureJson(raw);

        doc.Title.ShouldBe("Demo Architecture");
        doc.Layers.Count.ShouldBe(1);
        doc.KeyComponents[0].Path.ShouldBe("src/Cli/Program.cs");
        doc.MermaidDiagram.ShouldNotBeNull();
        doc.MermaidDiagram!.ShouldContain("flowchart");
    }

    [Fact]
    public async Task GenerateAsync_UsesOfflineWhenLlmUnavailable()
    {
        var llm = new Mock<ILlmCompletionService>();
        llm.Setup(x => x.CanUseLiveLlm(It.IsAny<AgentWikiConfig>(), It.IsAny<string?>()))
            .Returns(false);

        var prompts = new PromptManager(NullLogger<PromptManager>.Instance);
        var sut = new ArchitectureGenerator(llm.Object, prompts, NullLogger<ArchitectureGenerator>.Instance);

        var analysis = CreateMinimalAnalysis();
        var doc = await sut.GenerateAsync(analysis, new AgentWikiConfig());

        doc.UsedOfflineFallback.ShouldBeTrue();
        doc.Summary.ShouldNotBeNullOrWhiteSpace();
        llm.Verify(
            x => x.CompleteAsync(
                It.IsAny<AgentWikiConfig>(),
                It.IsAny<string>(),
                It.IsAny<string>(),
                It.IsAny<string?>(),
                It.IsAny<string?>(),
                It.IsAny<LlmRequestOptions?>(),
                It.IsAny<CancellationToken>()),
            Times.Never);
    }

    [Fact]
    public async Task GenerateAsync_ParsesLiveLlmJson()
    {
        var llm = new Mock<ILlmCompletionService>();
        llm.Setup(x => x.CanUseLiveLlm(It.IsAny<AgentWikiConfig>(), It.IsAny<string?>()))
            .Returns(true);
        llm.Setup(x => x.CompleteAsync(
                It.IsAny<AgentWikiConfig>(),
                It.IsAny<string>(),
                It.IsAny<string>(),
                It.IsAny<string?>(),
                It.IsAny<string?>(),
                It.IsAny<LlmRequestOptions?>(),
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(new LlmCompletionResult
            {
                Content = """
                    {
                      "title": "Live Architecture",
                      "summary": "Generated by mock LLM.",
                      "systemContext": "Mocked.",
                      "layers": [],
                      "keyComponents": [],
                      "dataFlows": [],
                      "decisions": [],
                      "gotchas": [],
                      "howToExtend": []
                    }
                    """,
                TokenUsage = new TokenUsage { InputTokens = 10, OutputTokens = 20 },
                Provider = "mock",
                Model = "test"
            });

        var prompts = new PromptManager(NullLogger<PromptManager>.Instance);
        var sut = new ArchitectureGenerator(llm.Object, prompts, NullLogger<ArchitectureGenerator>.Instance);

        var doc = await sut.GenerateAsync(CreateMinimalAnalysis(), new AgentWikiConfig());

        doc.UsedOfflineFallback.ShouldBeFalse();
        doc.Title.ShouldBe("Live Architecture");
        doc.TokenUsage!.InputTokens.ShouldBe(10);
        doc.TokenUsage.OutputTokens.ShouldBe(20);
    }

    [Fact]
    public async Task GenerateAsync_FallsBackWhenLlmThrows()
    {
        var llm = new Mock<ILlmCompletionService>();
        llm.Setup(x => x.CanUseLiveLlm(It.IsAny<AgentWikiConfig>(), It.IsAny<string?>()))
            .Returns(true);
        llm.Setup(x => x.CompleteAsync(
                It.IsAny<AgentWikiConfig>(),
                It.IsAny<string>(),
                It.IsAny<string>(),
                It.IsAny<string?>(),
                It.IsAny<string?>(),
                It.IsAny<LlmRequestOptions?>(),
                It.IsAny<CancellationToken>()))
            .ThrowsAsync(new InvalidOperationException("boom"));

        var prompts = new PromptManager(NullLogger<PromptManager>.Instance);
        var sut = new ArchitectureGenerator(llm.Object, prompts, NullLogger<ArchitectureGenerator>.Instance);

        var doc = await sut.GenerateAsync(CreateMinimalAnalysis(), new AgentWikiConfig());

        doc.UsedOfflineFallback.ShouldBeTrue();
        doc.Gotchas.Any(g => g.Contains("boom", StringComparison.Ordinal)).ShouldBeTrue();
    }

    private static RepoAnalysisResult CreateMinimalAnalysis()
    {
        var files = new List<RepoFile>
        {
            new()
            {
                RelativePath = "src/App/Program.cs",
                AbsolutePath = "/tmp/src/App/Program.cs",
                Category = FileCategory.SourceCode,
                SizeBytes = 100,
                Extension = ".cs",
                Language = "C#",
                LineCount = 10,
                SelectedForAnalysis = true
            }
        };

        var stats = new RepoStats
        {
            TotalFiles = 1,
            SelectedFiles = 1,
            TotalSizeBytes = 100,
            TotalLines = 10,
            FilesByCategory = new Dictionary<FileCategory, int> { [FileCategory.SourceCode] = 1 },
            FilesByExtension = new Dictionary<string, int> { [".cs"] = 1 },
            FilesByLanguage = new Dictionary<string, int> { ["C#"] = 1 },
            TopFolders = [new FolderStat("src", 1, 100)],
            DetectedLanguages = ["C#"]
        };

        return new RepoAnalysisResult
        {
            RepoPath = "/tmp/repo",
            RepoName = "repo",
            Files = files,
            Stats = stats,
            Summary = RepoSummaryBuilder.Build("repo", "/tmp/repo", stats, files),
            DiscoveryMethod = "FileSystemWalk"
        };
    }
}
