using System.Text;
using AgentWiki.Core.Models;

namespace AgentWiki.Core.Generation;

/// <summary>
/// Builds the full human-owned workspace contribution manifest template.
/// The scaffold documents purpose, maintenance rules, and all data sections in-file.
/// </summary>
public static class WorkspaceManifestScaffold
{
    /// <summary>
    /// Resolves the absolute path of the workspace contribution manifest for a member wiki root.
    /// </summary>
    public static string ResolvePath(string wikiOutputPath) =>
        Path.Combine(
            wikiOutputPath.TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar),
            Constants.WorkspaceManifest.FileName);

    /// <summary>
    /// Resolves the absolute path given a repo root and wiki path relative to the repo
    /// (or absolute wiki path).
    /// </summary>
    public static string ResolvePath(string repoPath, string wikiPathRelativeOrAbsolute)
    {
        var wikiAbs = Path.IsPathRooted(wikiPathRelativeOrAbsolute)
            ? Path.GetFullPath(wikiPathRelativeOrAbsolute)
            : Path.GetFullPath(Path.Combine(repoPath, wikiPathRelativeOrAbsolute));
        return ResolvePath(wikiAbs);
    }

    /// <summary>Returns the full Markdown template (never overwrites — callers check existence).</summary>
    public static string BuildTemplate()
    {
        var brands = string.Join(", ", Constants.WorkspaceManifest.KnownBrands);
        var layers = string.Join(" | ", Constants.WorkspaceManifest.SuggestedLayers);

        var sb = new StringBuilder();
        sb.AppendLine("# Workspace contribution manifest");
        sb.AppendLine();
        sb.AppendLine("## Purpose");
        sb.AppendLine();
        sb.AppendLine("This file is the **human-owned** contract between this repository and any AgentWiki");
        sb.AppendLine("**workspace** that includes it. Workspace generate **ingests** this file to build");
        sb.AppendLine("routing cards and the estate knowledge base used by multi-repo agents (and later");
        sb.AppendLine("search / MCP). It is **not** regenerated by AgentWiki except for initial scaffold");
        sb.AppendLine("when missing.");
        sb.AppendLine();
        sb.AppendLine("Deep implementation detail still lives in `docs/wiki/` (architecture, modules, APIs).");
        sb.AppendLine("This manifest answers: **what this repo is for, which apps it owns, which brands it");
        sb.AppendLine("supports, which layer it sits on, who owns it, and when work should (or should not)");
        sb.AppendLine("be routed here.**");
        sb.AppendLine();
        sb.AppendLine("## Maintenance rules");
        sb.AppendLine();
        sb.AppendLine("1. **Humans edit this file** in the same PRs that change ownership, layering, brands,");
        sb.AppendLine("   applications, or routing intent. Agents may propose edits; humans approve.");
        sb.AppendLine("2. **Do not delete required section headings** — tooling parses by heading text.");
        sb.AppendLine("3. Prefer **short bullets** under routing sections; put long narrative under");
        sb.AppendLine("   Additional context.");
        sb.AppendLine("4. Keep **Layer** and **Brands** accurate — incorrect values cause mis-routing across");
        sb.AppendLine("   similarly named APIs.");
        sb.AppendLine("5. List every **Application/Service** this repo truly owns or ships; omit unrelated");
        sb.AppendLine("   systems that only call this repo.");
        sb.AppendLine("6. After material changes, re-run member `agent-wiki generate` / `update` if needed,");
        sb.AppendLine("   then workspace `generate` so the estate KB refreshes.");
        sb.AppendLine("7. Do not put secrets, connection strings, or credentials in this file.");
        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine($"## {Constants.WorkspaceManifest.HeadingLayer}");
        sb.AppendLine();
        sb.AppendLine(layers);
        sb.AppendLine();
        sb.AppendLine($"## {Constants.WorkspaceManifest.HeadingTeam}");
        sb.AppendLine();
        sb.AppendLine("@team-or-name");
        sb.AppendLine();
        sb.AppendLine($"## {Constants.WorkspaceManifest.HeadingApplications}");
        sb.AppendLine();
        sb.AppendLine("- ApplicationOrServiceName — short description of what it does");
        sb.AppendLine("- …");
        sb.AppendLine();
        sb.AppendLine($"## {Constants.WorkspaceManifest.HeadingBrands}");
        sb.AppendLine();
        sb.AppendLine(brands);
        sb.AppendLine();
        sb.AppendLine(
            "(Comma-separated and/or bullets. Use only applicable brands. Blueprint = dummy/non-prod brand used for templates and demos.)");
        sb.AppendLine();
        sb.AppendLine($"## {Constants.WorkspaceManifest.HeadingResponsibilities}");
        sb.AppendLine();
        sb.AppendLine("- …");
        sb.AppendLine();
        sb.AppendLine($"## {Constants.WorkspaceManifest.HeadingRouteWhen}");
        sb.AppendLine();
        sb.AppendLine("- …");
        sb.AppendLine();
        sb.AppendLine($"## {Constants.WorkspaceManifest.HeadingDoNotRoute}");
        sb.AppendLine();
        sb.AppendLine("- …");
        sb.AppendLine();
        sb.AppendLine($"## {Constants.WorkspaceManifest.HeadingRelatedSystems}");
        sb.AppendLine();
        sb.AppendLine("- …");
        sb.AppendLine();
        sb.AppendLine($"## {Constants.WorkspaceManifest.HeadingKeywords}");
        sb.AppendLine();
        sb.AppendLine("keyword-one, keyword-two, …");
        sb.AppendLine();
        sb.AppendLine($"## {Constants.WorkspaceManifest.HeadingAdditionalContext}");
        sb.AppendLine();
        sb.AppendLine("Free-form Markdown always ingested into the workspace routing card.");
        sb.AppendLine();

        return EnsureTrailingNewline(sb.ToString());
    }

    /// <summary>
    /// Scaffolds the manifest under the wiki output path when missing.
    /// Never overwrites an existing file. Dry-run reports without writing.
    /// </summary>
    public static async Task<WorkspaceManifestScaffoldResult> EnsureAsync(
        string wikiOutputPath,
        bool dryRun = false,
        CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(wikiOutputPath);

        try
        {
            var path = ResolvePath(wikiOutputPath);
            if (File.Exists(path))
            {
                return WorkspaceManifestScaffoldResult.AlreadyExists(path);
            }

            if (dryRun)
            {
                return WorkspaceManifestScaffoldResult.CreatedOk(path, dryRun: true);
            }

            var dir = Path.GetDirectoryName(path);
            if (!string.IsNullOrEmpty(dir))
            {
                Directory.CreateDirectory(dir);
            }

            var content = BuildTemplate();
            await File.WriteAllTextAsync(path, content, cancellationToken).ConfigureAwait(false);
            return WorkspaceManifestScaffoldResult.CreatedOk(path, dryRun: false);
        }
        catch (Exception ex)
        {
            return WorkspaceManifestScaffoldResult.Fail(
                $"Failed to scaffold workspace contribution manifest: {ex.Message}");
        }
    }

    private static string EnsureTrailingNewline(string text) =>
        text.EndsWith('\n') ? text : text + Environment.NewLine;
}
